[package]
name = "bubbaloop"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Protobuf schemas for bubbaloop"

[dependencies]
prost.workspace = true
prost-types.workspace = true
serde.workspace = true
ros-z.workspace = true

[build-dependencies]
prost-build.workspace = true
