[package]
name = "bubbaloop"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Protobuf schemas for bubbaloop"

[dependencies]
prost.workspace = true
prost-types.workspace = true
prost-reflect.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
ros-z.workspace = true
argh.workspace = true
tokio.workspace = true
env_logger.workspace = true
log.workspace = true

[build-dependencies]
prost-build.workspace = true

[[bin]]
name = "bubbaloop"
path = "src/bin/bubbaloop.rs"
